include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - require_trailing_commas
    - prefer_relative_imports
    - unnecessary_parenthesis
    - use_enums
    - use_colored_box
    - use_decorated_box

