name: proxima_logger
description: Easy to use, customizable, expandable logger that prints beautiful logs.
version: 0.5.1
repository: https://github.com/StarProxima/proxima_logger
homepage: https://github.com/StarProxima

environment:
  sdk: '>=2.18.6 <3.0.0'
