name: proxima_logger
description: Easy to use, customizable, expandable logger that prints beautiful logs.
version: 0.7.2
repository: https://github.com/StarProxima/proxima_logger
homepage: https://github.com/StarProxima

environment:
  sdk: '>=2.17.0 <4.0.0'

dev_dependencies:
  test: ^1.22.1